//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENTAL.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Booking_details
    {
        public int booking_details_id { get; set; }
        public Nullable<int> booking_id { get; set; }
        public Nullable<int> car_id { get; set; }
        public string booking_details_status { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> actual_return_date { get; set; }
        public Nullable<decimal> price_per_car { get; set; }
        public Nullable<decimal> fine { get; set; }
        public Nullable<decimal> refund { get; set; }
        public Nullable<int> status_return { get; set; }
    
        public virtual tbl_Booking tbl_Booking { get; set; }
        public virtual tbl_Car tbl_Car { get; set; }
    }
}
