//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENTAL.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Booking()
        {
            this.tbl_Booking_details = new HashSet<tbl_Booking_details>();
        }
    
        public int booking_id { get; set; }
        public Nullable<int> cus_id { get; set; }
        public string booking_status { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> deposit { get; set; }
        public Nullable<int> payment_type_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> paid { get; set; }
        public Nullable<decimal> deposit_cash { get; set; }
        public Nullable<int> deposit_cash_has_paid { get; set; }
        public Nullable<int> payment_confirm { get; set; }
        public Nullable<int> is_cancel { get; set; }
        public string reason_cancel { get; set; }
        public Nullable<System.DateTime> complete_date { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public Nullable<int> pickup_method { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Booking_details> tbl_Booking_details { get; set; }
        public virtual tbl_Payment_type tbl_Payment_type { get; set; }
    }
}
