//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENTAL.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer()
        {
            this.tbl_Booking = new HashSet<tbl_Booking>();
        }
    
        public int cus_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> active { get; set; }
        public string cus_id_card { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string name { get; set; }
        public Nullable<int> district_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Booking> tbl_Booking { get; set; }
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_District tbl_District { get; set; }
    }
}
