//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENTAL.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Car()
        {
            this.tbl_Booking_details = new HashSet<tbl_Booking_details>();
        }
    
        public int car_id { get; set; }
        public Nullable<int> cate_id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<decimal> price_per_day { get; set; }
        public string car_status { get; set; }
        public string image { get; set; }
        public string license_plate { get; set; }
        public Nullable<int> seat_count { get; set; }
        public string color { get; set; }
        public Nullable<int> car_type_id { get; set; }
        public Nullable<int> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Booking_details> tbl_Booking_details { get; set; }
        public virtual tbl_Car_type tbl_Car_type { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
